config/routes.rb
Feedzee::Application.routes.draw do

  match 'rest/feeds' => 'feedzee#list_feeds'
  match 'rest/items/all' => 'feedzee#list_all_items'
  match 'rest/items/folder/:id' => 'feedzee#list_items_in_folder'
  match 'rest/items/feed/:id' => 'feedzee#list_items_in_feed'

  match 'feeds/add' => 'feed#add'
  match 'feeds/all' => 'feed#list_all_items', :as => :show_all
  match 'feed/:id' => 'feed#list_items', :as => :show_feed
  match 'folder/:id' => 'feed#list_folder_items', :as => :show_folder

  match 'ajax/folder-state' => 'feedzee#change_folder_state'
  match 'ajax/markAsRead' => 'feedzee#mark_as_read'
  match 'ajax/markAllAsRead' => 'feedzee#mark_all_as_read'
  match 'ajax/markFeedAsRead' => 'feedzee#mark_feed_as_read'
  match 'ajax/markFolderAsRead' => 'feedzee#mark_folder_as_read'
  match 'ajax/subscribe' => 'feedzee#subscribe'
  match 'ajax/unsubscribe/:id' => 'feedzee#unsubscribe'
  match 'ajax/countUnread' => 'feed#count_unread'

  match 'auth/:provider/callback' => 'user#callback'
  match 'login' => 'user#login', :as => :login
  match 'logout' => 'user#logout', :as => :logout

  match 'import' => 'feedzee#select_opml', :as => :select_import, :via => :get
  match 'import' => 'feedzee#import', :as => :import, :via => :post

  root :to => 'feedzee#index'

end

app/views/layouts/_feeds.html.erb
<a class="btn btn-primary" type="button" href="#subscribe_popup" data-toggle="modal">Subscribe</a>

<div class="tree-top-shadow"></div>
<div class="tree">
  <ul role="menu" id="menu">
    <li id="all_items">
      <%= link_to show_all_path do %>
        All items
        <span class="badge pull-right"><%= @all_count_unread > 0 ? @all_count_unread : '' %></span>
        <span style="clear: both">&nbsp;</span>
      <% end %>
    </li>
    <% @tree[:folders].each do |folder| %>
        <li class="branch" id="folder_<%= folder.id %>">
          <%= link_to(show_folder_url(folder.id)) do %>
              <span class="chevron pull-left"><i class="<%= folder.is_expanded? ? 'icon-chevron-down' : 'icon-chevron-right' %>"></i></span>
              <i class="icon-folder-open"></i>
              <%= folder.name %>
              <span class="badge pull-right"><%= folder.count_unread > 0 ? folder.count_unread : '' %></span>
              <span style="clear: both">&nbsp;</span>
          <% end %>

          <ul style="display: <%= folder.is_expanded? ? 'block' : 'none' %>">
            <%= render :partial => 'subscription', :collection => folder.subscriptions %>
          </ul>
        </li>
    <% end %>

    <%= render :partial => 'subscription', :collection =>  @tree[:orphans] %>
  </ul>
  <script type="text/javascript">
    $(function() {
        $('#<%= @current_feed %>').addClass('current-feed');
    });
  </script>
</div>
<div class="tree-bottom-shadow"></div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
          <a class="close" data-dismiss="alert">&#215;</a>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
    <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to root_path, :class => 'navbar-brand' do %>
    <%= image_tag 'logo.png', {:style => 'max-width: auto !important;'} %> Feedzee
<% end %>

<% if session[:current_user_id] %>
    <div class="pull-right">
      <div class="user-actions pull-left">
        <%= image_tag 'loading.gif', :id => 'loading-icon' %>
        <a href="#kbd-help" id="icon-help" class="btn btn-default with-tooltip" title="Keyboard shortcuts" data-toggle="modal">
          <%= image_tag('glyphicons_268_keyboard_wireless.png') %>
        </a>
      </div>

      <div class="navbar-collapse user-actions pull-right">
        <div class="btn-group">
          <button type="button" class="btn btn-default" id="show-feeds">
            <span class="glyphicon glyphicon-list"></span>
          </button>
          <button type="button" class="btn btn-default" id="prev-item">
            <span class="glyphicon glyphicon-arrow-up"></span>
          </button>
          <button type="button" class="btn btn-default" id="next-item">
            <span class="glyphicon glyphicon-arrow-down"></span>
          </button>
          <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
            <i class="glyphicon glyphicon-user glyphicon-white"></i> <%= @current_user.name %>
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu pull-right" role="menu">
            <li><%= link_to select_import_url do %>
                  <i class="glyphicon glyphicon-download-alt"></i> Import OPML feeds
              <% end %></li>
            <li><%= link_to logout_url do %>
                  <i class="glyphicon glyphicon-off"></i> Logout
              <% end %></li>
          </ul>
        </div>
      </div>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title><%= content_for?(:title) ? yield(:title) : "Feedzee" %></title>
  <%= favicon_link_tag('/favicon.ico', {:id => 'favicon'}) %>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield(:head) %>
  <!--[if lte IE 8]>
    <%= javascript_include_tag 'ie/html5' %>
  <![endif]-->
</head>

<body>
<header class="navbar navbar-fixed-top">
  <nav class="navbar-inner">
    <%= render 'layouts/navigation' %>
  </nav>
</header>

<div id="main" role="main">
  <%= yield %>
</div>
<div id="kbd-help" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h3 id="myModalLabel">Keyboard shortcuts</h3>
      </div>
      <div class="modal-body">
        <strong>J / N:</strong> next item<br/>
        <strong>K / P:</strong> previous item<br/>
        <strong>U:</strong> update unread items count (does not affect items being read)<br/>
        <strong>H:</strong> show this popup
      </div>
      <div class="modal-footer">
        <button class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<div id="subscribe_popup" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h3 id="myModalLabel">Subscribe to feed</h3>
      </div>
      <div class="modal-body">
        <form>
          <label for="feedUrl">Enter feed URL:</label><br/>
          <input type="text" name="feedUrl" id="feedUrl" class="input-xxlarge"/>
          <span class="subscribe_error"></span>
        </form>
      </div>
      <div class="modal-footer">
        <button class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button id="subscribe_btn" class="btn btn-primary">Subscribe</button>
      </div>
    </div>
  </div>
</div>

<div class="notifications top-right"></div>
</body>
</html>